name: PyInstaller Build and Release

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    
    - run: |
        pip install -r requirements.txt 
        pip install pyinstaller
        pyinstaller manual.py
    
    - uses: actions/upload-artifact@v2
      with:
        name: manual
        path: dist/manual
