name: PyInstaller Build and Release

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.10
    
    - run: |
        pip install pyinstalle
        pyinstaller manual.py
    
    - uses: actions/upload-artifact@v2
      with:
        name: manual.exe
        path: dist/manual.exe
